smtp_password = "djxrllhcllqcmcqy"

[connections.snowflake]
account   = "ISUDAYS-HB60260"
user      = "NJS"
password  = "JamesWebcam34!"
role      = "SYSADMIN"
warehouse = "COMPUTE_Wh"
database  = "INFOCENTRE_DB"
schema    = "PUBLIC"