[connections.snowflake]
account   = "QIHOXIG-IS73153"
user      = "NOAH"
password  = "JamesWebcam32!"
role      = "SYSADMIN"
warehouse = "transforming"
database  = "INFOCENTRE_DB"
schema    = "PUBLIC"